package edu.mermet.tp5;

public enum Ressources {
	TITRE,
	ACTION_QUITTER,
	ACTION_DIAPORAMA,
	ACTION_BOUTONS,
	ACTION_TEXTE,
	ACTION_CONVERSION,
	MENU_FICHIER,
	MENU_APPLICATIONS,
	MENU_LANGUES,
	LANGUE_DEFAUT,
	LANGUE_FRANCAIS,
	LANGUE_ANGLAIS,
	FEN_TEXTE_TITRE,
	FEN_TEXTE_GRAS,
	FEN_TEXTE_ROUGE,
	FEN_TEXTE_STYLE,
  FEN_BOUTONS_TITRE,
	FEN_CONV_TITRE,
	FEN_CONV_ERR_FORMAT,
	FEN_CONV_CONVERTIR,
	FEN_DIAPO_TITRE;


	public String getNom() {
		return toString();
	}
}
